#!/bin/sh
# Quickly switch to requested layout
CACHE="$XDG_CACHE_HOME/dwm"

[ -d "$CACHE" ] || mkdir -p "$CACHE"
[ -e "$CACHE/keylays-hist" ] || echo 'us' >> "$CACHE/keylays-hist"

addentry(){ grep -q "$LAYOUT" "$CACHE/keylays-hist" || echo "$LAYOUT" >> "$CACHE/keylays-hist"; }
LAYOUT=$( printf '%s\n' $(cat "$CACHE/keylays-hist") | dmenu "$@" )

if echo $LAYOUT | grep -qE '^-'; then
	LAYOUT=$(echo $LAYOUT | sed 's/^-//')
	sed -i "/$LAYOUT/d" "$CACHE/keylays-hist"
	[ "$( setxkbmap -query | awk '/layout:/ {print $NF}' )" = "$LAYOUT" ] && setxkbmap -layout $( head -n 1 "$CACHE/keylays-hist" || echo us )
else 
	setxkbmap -layout $LAYOUT && addentry
fi

kill -41 "$( pidof dwmblocks )"
