#!/bin/sh
ACTION="$( echo "hibernate\nshutdown\nsleep\nreboot\nlock\nlog out\nrestart dwm" | dmenu )"
case $ACTION in
	'hibernate') slock & systemctl hibernate;;
	'shutdown') sudo shutdown now;;
	'sleep') slock & systemctl suspend;;
	'reboot') sudo reboot;;
	'lock') slock;;
	'log out') kill -TERM "$(pidof dwm)";;
	'restart dwm') kill -HUP "$(pidof dwm)";;
	*) echo error;;
esac
