#!/bin/sh
# toggle left mon on and off
if xrandr --listactivemonitors | grep -q HDMI-0; then
	xrandr --output HDMI-0 --off
else
	xrandr --output HDMI-0 --mode 1366x768 --left-of DP-0
fi

xwallpaper --zoom .config/wall
